In [1]:

import geopandas as gpd
import pandas as pd

import mercantile
from tqdm import tqdm
import json

from datetime import datetime, timezone
import requests

from vt2geojson.tools import vt_bytes_to_geojson

import os

from concurrent.futures import ThreadPoolExecutor, as_completed
#import threading


import gzip


from requests.exceptions import SSLError
import time

In [2]:
def load_tiles_from_json(bundesland_id, input_folder="prep/tile_cache"):
    path = os.path.join(input_folder, f"{bundesland_id}_tiles.json")
    with open(path, "r") as f:
        tile_list = json.load(f)
    return [mercantile.Tile(**t) for t in tile_list]

In [3]:

def export_geodata(
    gdfs,
    output_folder="output",
    base_name="mapillary_map-feature-points",
    region="ger",
    save_parquet=True,
    save_geojson_gz=True,
    metadata_path=None,
    bundesland_id=None,
):
    if gdfs is None or (isinstance(gdfs, (gpd.GeoDataFrame, pd.DataFrame)) and gdfs.empty):
        print("No data to export.")
        return

    if isinstance(gdfs, list):
        gdf_concat = pd.concat(gdfs, ignore_index=True)
        crs = None
        try:
            if len(gdfs) > 0 and getattr(gdfs[0], "crs", None) is not None:
                crs = gdfs[0].crs
        except Exception:
            crs = None
        gdf = gpd.GeoDataFrame(gdf_concat, crs=crs)
    else:
        gdf = gdfs

    os.makedirs(output_folder, exist_ok=True)
    current_timestamp = datetime.now(timezone.utc).isoformat()

    # Update metadata (ml-mf_metadata.json) similar to ml-ts_metadata.json
    if bundesland_id:
        if metadata_path is None:
            metadata_path = os.path.join(output_folder, "ml-mf_metadata.json")
        if os.path.exists(metadata_path):
            with open(metadata_path, "r", encoding="utf-8") as f:
                metadata = json.load(f)
        else:
            metadata = {
                "ml_data_from": None,
                "bundeslaender": {},
                "processed_date": None,
            }

        metadata["bundeslaender"][bundesland_id] = current_timestamp
        if metadata.get("bundeslaender"):
            metadata["ml_data_from"] = min(metadata["bundeslaender"].values())
        metadata["processed_date"] = datetime.now(timezone.utc).isoformat()

        with open(metadata_path, "w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=2, ensure_ascii=False)

    if save_parquet:
        parquet_path = os.path.join(output_folder, f"{base_name}_{region}_latest.parquet")
        gdf.to_parquet(parquet_path, index=False)
        print(f"✔ Parquet saved to: {parquet_path}")

    if save_geojson_gz:
        geojson_path = os.path.join(output_folder, f"{base_name}_{region}_latest.geojson")
        gz_path = geojson_path + ".gz"

        gdf.to_file(geojson_path, driver="GeoJSON")

        with open(geojson_path, "rb") as f_in, gzip.open(gz_path, "wb") as f_out:
            f_out.writelines(f_in)

        os.remove(geojson_path)
        print(f"✔ Gzipped GeoJSON saved to: {gz_path}")

In [4]:
def process_bundesland(bundesland_id, region_name=None, input_folder="prep/tile_cache", output_folder="output", max_workers=3, limit_tiles=None):
    print(f"▶️ Starte Verarbeitung für {bundesland_id}...")

    metadata_path = os.path.join(output_folder, "ml-mf_metadata.json")

    tiles = load_tiles_from_json(bundesland_id, input_folder=input_folder)
    if limit_tiles:
        tiles = tiles[:limit_tiles]

    def process_tile(tile):

        # Load your access token
        with open("config.json") as f:
            ACCESS_TOKEN = json.load(f)["ACCESS_TOKEN"]

        # Use existing variables
        tile_layer = 'point'  # #'traffic_sign'  # already defined
        tile_coverage =  'mly_map_feature_point' #"mly_map_feature_traffic_sign"
        
        url = f"https://tiles.mapillary.com/maps/vtp/{tile_coverage}/2/{tile.z}/{tile.x}/{tile.y}?access_token={ACCESS_TOKEN}"
        response = requests.get(url)
        if response.status_code != 200:
            return None
        try:
            geojson = vt_bytes_to_geojson(response.content, tile.x, tile.y, tile.z, layer=tile_layer)
            features = geojson.get("features", [])
            if not features:
                return None
            gdf_tile = gpd.GeoDataFrame.from_features(features, crs="EPSG:4326")
            gdf_tile['first_seen_at'] = gdf_tile['first_seen_at'].apply(lambda x: datetime.fromtimestamp(x / 1000, tz=timezone.utc)).dt.strftime('%Y-%m-%d')
            gdf_tile['last_seen_at'] = gdf_tile['last_seen_at'].apply(lambda x: datetime.fromtimestamp(x / 1000, tz=timezone.utc)).dt.strftime('%Y-%m-%d')
            gdf_tile['tile_x'] = tile.x
            gdf_tile['tile_y'] = tile.y
            return gdf_tile
        except Exception as e:
            print(f"❌ Fehler bei Tile {tile.x}/{tile.y}: {e}")
            return None

    gdf_all = []
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(process_tile, tile): tile for tile in tiles}
        for future in tqdm(as_completed(futures), total=len(futures), desc=f"🧩 {bundesland_id}"): #, leave=False
            try:
                result = future.result()
                if result is not None:
                    gdf_all.append(result)
            except SSLError as e:
                print(f"⚠️ SSLError: {e}. Pausiere für 5 Minuten...")
                time.sleep(300)  # 5 Minuten Pause
            except Exception as e:
                print(f"⚠️ Unbekannter Fehler: {e}")

    if gdf_all:
        gdf_all = gpd.GeoDataFrame(pd.concat(gdf_all, ignore_index=True))
        export_geodata(
            gdfs=gdf_all,
            output_folder=output_folder,
            region=bundesland_id,
            save_parquet=True,
            save_geojson_gz=False,
            metadata_path=metadata_path,
            bundesland_id=bundesland_id,
        )
    else:
        print(f"⚠️ Keine Daten für {bundesland_id}.")

In [5]:
bland = gpd.read_file("https://raw.githubusercontent.com/isellsoap/deutschlandGeoJSON/main/2_bundeslaender/1_sehr_hoch.geo.json")
bland#[15:]

,id,name,type,geometry
0,DE-BW,Baden-Württemberg,State,"MULTIPOLYGON (((8.70837 47.71556, 8.70918 47.7..."
1,DE-BY,Bayern,State,"POLYGON ((10.13386 50.55, 10.1398 50.54252, 10..."
2,DE-BE,Berlin,State,"POLYGON ((13.16181 52.59442, 13.174 52.59425, ..."
3,DE-BB,Brandenburg,State,"POLYGON ((13.87951 53.50107, 13.87927 53.49908..."
4,DE-HB,Bremen,State,"POLYGON ((8.98545 53.12822, 8.97316 53.12799, ..."
5,DE-HH,Hamburg,State,"POLYGON ((10.07162 53.71823, 10.0715 53.72192,..."
6,DE-HE,Hessen,State,"POLYGON ((9.49877 51.63152, 9.50474 51.62795, ..."
7,DE-MV,Mecklenburg-Vorpommern,State,"MULTIPOLYGON (((14.26472 53.71069, 14.26472 53..."
8,DE-NI,Niedersachsen,State,"MULTIPOLYGON (((6.86528 53.59597, 6.86528 53.5..."
9,DE-NW,Nordrhein-Westfalen,State,"POLYGON ((8.66628 52.52528, 8.67277 52.51795, ..."
10,DE-RP,Rheinland-Pfalz,State,"POLYGON ((7.79963 50.94302, 7.81179 50.93973, ..."
11,DE-SL,Saarland,State,"POLYGON ((7.03796 49.64338, 7.0559 49.63674, 7..."
12,DE-ST,Sachsen-Anhalt,State,"POLYGON ((11.63251 53.01641, 11.63239 53.00897..."
13,DE-SN,Sachsen,State,"POLYGON ((12.878 51.6727, 12.87185 51.6691, 12..."
14,DE-SH,Schleswig-Holstein,State,"MULTIPOLYGON (((8.68972 54.06681, 8.68972 54.0..."
15,DE-TH,Thüringen,State,"POLYGON ((10.77189 51.64491, 10.78391 51.64098..."

In [6]:
bland[4:5]

      id    name   type                                           geometry
4  DE-HB  Bremen  State  POLYGON ((8.98545 53.12822, 8.97316 53.12799, ...

In [7]:


# Alle Bundesländer im tile_cache verarbeiten

bland = gpd.read_file("https://raw.githubusercontent.com/isellsoap/deutschlandGeoJSON/main/2_bundeslaender/1_sehr_hoch.geo.json")

#for _, row in bland[4:5].iterrows():
#for _, row in bland[15:].iterrows():
for _, row in bland.iterrows():

    b_id = row["id"]
    name = row["name"]

    # Nur verarbeiten, wenn eine JSON-Datei existiert
    tile_json_path = os.path.join("prep/tile_cache", f"{b_id}_tiles.json")
    if not os.path.exists(tile_json_path):
        print(f"⏩ Überspringe {b_id}, keine Tiles gefunden.")
        continue

    process_bundesland(b_id, region_name=name)

▶️ Starte Verarbeitung für DE-BW...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-BW_latest.parquet

▶️ Starte Verarbeitung für DE-BY...

/usr/local/lib/python3.12/site-packages/vt2geojson/tools.py:27: DeprecationWarning: `decode` signature has changed, use `default_options` instead
  data = decode(b_content, y_coord_down=True)

✔ Parquet saved to: output/mapillary_map-feature-points_DE-BY_latest.parquet

▶️ Starte Verarbeitung für DE-BE...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-BE_latest.parquet

▶️ Starte Verarbeitung für DE-BB...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-BB_latest.parquet

▶️ Starte Verarbeitung für DE-HB...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-HB_latest.parquet
▶️ Starte Verarbeitung für DE-HH...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-HH_latest.parquet

▶️ Starte Verarbeitung für DE-HE...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-HE_latest.parquet

▶️ Starte Verarbeitung für DE-MV...

❌ Fehler bei Tile 8675/5307: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8677/5302: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8677/5306: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8677/5305: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8678/5305: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8679/5302: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8679/5303: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8679/5305: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8680/5300: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8680/5303: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8681/5310: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8682/5271: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8682/5303: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8683/5306: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8683/5304: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8683/5310: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8684/5269: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8683/5312: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8684/5270: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8684/5274: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8684/5296: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8684/5297: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8684/5298: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8685/5276: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8685/5279: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8685/5296: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8685/5305: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8685/5307: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8685/5308: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8685/5309: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8685/5311: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8686/5269: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8686/5271: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8686/5272: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8686/5282: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8686/5296: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8686/5301: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8687/5266: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8687/5267: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8687/5270: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8687/5272: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8687/5276: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8687/5306: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8687/5308: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8687/5311: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8688/5270: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8688/5274: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8688/5282: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8688/5302: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8688/5304: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8688/5308: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8689/5265: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8689/5271: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8689/5281: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8689/5299: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8689/5301: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8690/5267: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8690/5269: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8690/5270: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8690/5274: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8690/5275: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8690/5281: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8690/5282: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8690/5293: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8690/5292: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8690/5294: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8690/5296: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8690/5309: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8691/5259: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8691/5270: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8691/5272: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8691/5275: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8691/5276: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8691/5278: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8691/5284: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8691/5287: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8691/5294: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8691/5296: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8691/5308: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8691/5309: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8692/5259: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8692/5260: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8692/5262: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8692/5263: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8692/5276: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8692/5281: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8692/5291: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8692/5296: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8692/5300: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8692/5311: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8693/5262: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8693/5267: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8693/5271: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8693/5278: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8693/5280: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8693/5281: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8693/5284: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8693/5292: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8693/5293: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8693/5301: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8693/5302: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8693/5306: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8694/5258: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8694/5259: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8694/5264: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8694/5265: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8694/5268: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8694/5286: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8694/5287: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8694/5288: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8694/5292: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8694/5293: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8694/5294: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8694/5314: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8695/5258: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8695/5262: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8695/5263: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8695/5265: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8695/5273: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8695/5275: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8695/5274: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8695/5276: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8695/5285: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8695/5286: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8695/5295: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8695/5301: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8695/5303: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8696/5258: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8696/5271: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8696/5274: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8696/5275: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8696/5276: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8696/5279: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8696/5283: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8696/5288: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8696/5290: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8696/5291: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8696/5299: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8696/5304: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8696/5306: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8696/5318: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8697/5280: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8697/5281: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8697/5287: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8697/5289: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8697/5294: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8697/5311: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8697/5313: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8698/5262: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8698/5263: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8698/5264: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8698/5269: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8698/5272: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8698/5277: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8698/5297: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8698/5303: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8698/5304: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8698/5312: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8698/5316: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8699/5272: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8699/5277: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8699/5278: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8699/5285: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8699/5288: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8699/5298: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8699/5305: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8699/5307: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8699/5312: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8700/5258: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8700/5277: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8700/5296: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8700/5297: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8700/5306: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8700/5308: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8700/5310: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8700/5314: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8701/5277: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8701/5286: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8701/5291: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8701/5294: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8701/5295: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8701/5296: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8701/5305: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8701/5311: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8701/5319: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8701/5323: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8702/5266: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8702/5268: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8702/5273: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8702/5271: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8702/5285: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8702/5294: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8702/5298: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8702/5305: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8702/5323: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8702/5325: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8703/5266: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8703/5272: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8703/5275: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8703/5291: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8703/5292: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8703/5312: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8703/5324: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8704/5266: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8704/5265: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8704/5269: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8704/5271: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8704/5280: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8704/5307: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8704/5310: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8705/5260: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8705/5266: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8705/5270: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8705/5271: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8705/5276: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8705/5279: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8705/5282: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8705/5287: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8705/5297: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8705/5299: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8705/5320: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8706/5275: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8706/5293: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8706/5294: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8706/5306: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8706/5324: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8707/5271: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8707/5273: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8707/5286: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8707/5296: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8707/5303: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8707/5309: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8707/5311: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8707/5318: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8708/5262: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8708/5264: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8708/5265: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8708/5271: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8708/5275: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8708/5285: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8708/5287: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8708/5291: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8708/5311: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8708/5315: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8708/5314: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8708/5324: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8709/5264: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8709/5269: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8709/5286: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8709/5291: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8709/5292: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8709/5299: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8709/5305: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8709/5308: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8709/5312: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8709/5323: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8710/5278: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8710/5286: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8710/5291: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8710/5293: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8710/5294: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8710/5298: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8710/5309: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8710/5314: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8710/5322: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8711/5257: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8711/5260: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8711/5302: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8711/5314: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8712/5268: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8712/5284: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8712/5298: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8712/5320: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8712/5323: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8713/5264: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8713/5277: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8713/5280: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8713/5283: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8713/5288: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8713/5294: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8713/5303: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8713/5321: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8714/5255: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8714/5260: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8714/5269: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8714/5292: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8714/5305: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8714/5323: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8715/5262: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8715/5271: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8715/5290: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8715/5299: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8715/5315: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8715/5321: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8716/5256: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8716/5258: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8716/5273: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8716/5280: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8716/5278: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8716/5292: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8717/5273: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8717/5272: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8717/5296: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8717/5300: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8717/5302: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8717/5308: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8718/5254: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8717/5309: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8718/5265: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8718/5288: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8718/5311: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8719/5268: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8719/5286: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8720/5251: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8720/5268: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8720/5274: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8720/5278: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8720/5280: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8720/5282: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8720/5299: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8721/5248: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8721/5251: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8721/5258: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8721/5279: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8721/5282: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8721/5302: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8721/5290: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8722/5273: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8722/5281: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8723/5247: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8723/5262: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8723/5269: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8723/5289: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8723/5307: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8723/5313: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8723/5316: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8724/5272: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8724/5289: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8724/5297: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8724/5312: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5263: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5270: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5274: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5277: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5312: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5248: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5250: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5274: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5278: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5286: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5309: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5310: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5267: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5269: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5279: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5285: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5288: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5297: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5315: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5247: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5254: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5257: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5264: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5271: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5294: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5254: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5263: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5274: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5285: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5295: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5310: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5253: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5280: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5287: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5266: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5277: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5294: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5297: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5305: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5311: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5250: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5257: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5290: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8733/5257: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8733/5266: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8733/5280: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8734/5260: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8734/5268: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8734/5297: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8734/5308: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8735/5263: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8735/5275: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8735/5279: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8735/5303: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8735/5310: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8736/5248: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8736/5311: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8738/5262: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8738/5274: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8738/5276: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8738/5292: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8739/5257: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8739/5261: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8740/5245: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8740/5260: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8741/5251: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8741/5293: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8742/5259: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8742/5264: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8742/5268: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8742/5294: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8742/5301: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8742/5305: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8743/5245: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8743/5293: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8744/5247: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8744/5261: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8744/5279: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8744/5288: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8744/5305: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8746/5249: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8746/5295: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8746/5297: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8746/5300: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8747/5296: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8748/5238: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8748/5248: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8749/5251: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8749/5274: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8749/5296: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8750/5243: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8750/5248: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8751/5243: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8754/5284: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8755/5299: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8756/5244: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8757/5229: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8757/5248: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8757/5259: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8757/5299: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8758/5244: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8758/5314: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8759/5244: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8759/5243: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8759/5276: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8759/5284: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8759/5304: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8760/5261: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8761/5226: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8761/5245: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8761/5249: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8761/5264: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8761/5276: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8761/5283: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8761/5287: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8761/5301: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8763/5241: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8763/5297: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8771/5283: Error parsing message with type 'vector_tile.tile'

✔ Parquet saved to: output/mapillary_map-feature-points_DE-MV_latest.parquet
▶️ Starte Verarbeitung für DE-NI...

❌ Fehler bei Tile 8588/5349: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8588/5356: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8588/5360: Error parsing message with type 'vector_tile.tile'

✔ Parquet saved to: output/mapillary_map-feature-points_DE-NI_latest.parquet

▶️ Starte Verarbeitung für DE-NW...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-NW_latest.parquet
▶️ Starte Verarbeitung für DE-RP...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-RP_latest.parquet

▶️ Starte Verarbeitung für DE-SL...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-SL_latest.parquet

▶️ Starte Verarbeitung für DE-ST...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-ST_latest.parquet

▶️ Starte Verarbeitung für DE-SN...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-SN_latest.parquet

▶️ Starte Verarbeitung für DE-SH...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-SH_latest.parquet

▶️ Starte Verarbeitung für DE-TH...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-TH_latest.parquet