In [1]:

import geopandas as gpd
import pandas as pd

import mercantile
from tqdm import tqdm
import json

from datetime import datetime, timezone
import requests

from vt2geojson.tools import vt_bytes_to_geojson

import os

from concurrent.futures import ThreadPoolExecutor, as_completed
#import threading


import gzip
import gc


from requests.exceptions import SSLError
import time

In [2]:
def load_tiles_from_json(bundesland_id, input_folder="prep/tile_cache"):
    path = os.path.join(input_folder, f"{bundesland_id}_tiles.json")
    with open(path, "r") as f:
        tile_list = json.load(f)
    return [mercantile.Tile(**t) for t in tile_list]

In [3]:

def export_geodata(
    gdfs,
    output_folder="output",
    base_name="mapillary_map-feature-points",
    region="ger",
    save_parquet=True,
    save_geojson_gz=True,
    metadata_path=None,
    bundesland_id=None,
):
    if gdfs is None or (isinstance(gdfs, (gpd.GeoDataFrame, pd.DataFrame)) and gdfs.empty):
        print("No data to export.")
        return

    if isinstance(gdfs, list):
        gdf_concat = pd.concat(gdfs, ignore_index=True)
        crs = None
        try:
            if len(gdfs) > 0 and getattr(gdfs[0], "crs", None) is not None:
                crs = gdfs[0].crs
        except Exception:
            crs = None
        gdf = gpd.GeoDataFrame(gdf_concat, crs=crs)
    else:
        gdf = gdfs

    os.makedirs(output_folder, exist_ok=True)
    current_timestamp = datetime.now(timezone.utc).isoformat()

    # Update metadata (ml-mf_metadata.json) similar to ml-ts_metadata.json
    if bundesland_id:
        if metadata_path is None:
            metadata_path = os.path.join(output_folder, "ml-mf_metadata.json")
        if os.path.exists(metadata_path):
            with open(metadata_path, "r", encoding="utf-8") as f:
                metadata = json.load(f)
        else:
            metadata = {
                "ml_data_from": None,
                "bundeslaender": {},
                "processed_date": None,
            }

        metadata["bundeslaender"][bundesland_id] = current_timestamp
        if metadata.get("bundeslaender"):
            metadata["ml_data_from"] = min(metadata["bundeslaender"].values())
        metadata["processed_date"] = datetime.now(timezone.utc).isoformat()

        with open(metadata_path, "w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=2, ensure_ascii=False)

    if save_parquet:
        parquet_path = os.path.join(output_folder, f"{base_name}_{region}_latest.parquet")
        gdf.to_parquet(parquet_path, index=False)
        print(f"✔ Parquet saved to: {parquet_path}")

    if save_geojson_gz:
        geojson_path = os.path.join(output_folder, f"{base_name}_{region}_latest.geojson")
        gz_path = geojson_path + ".gz"

        # Mapillary ids are larger than JS Number.MAX_SAFE_INTEGER (2**53). Written
        # as JSON numbers they get rounded to the nearest double by every JS
        # consumer (MapLibre, tippecanoe/PMTiles, web map, MapRoulette), which
        # breaks the resulting Mapillary links. Emit them as strings instead.
        # assign() only rebuilds the id columns, it is not a full frame copy -
        # the parquet written above keeps the lossless int64.
        id_cols = {c: gdf[c].astype("string") for c in ("id", "image_id") if c in gdf.columns}
        gdf_export = gdf.assign(**id_cols) if id_cols else gdf

        gdf_export.to_file(geojson_path, driver="GeoJSON")

        with open(geojson_path, "rb") as f_in, gzip.open(gz_path, "wb") as f_out:
            f_out.writelines(f_in)

        os.remove(geojson_path)
        print(f"✔ Gzipped GeoJSON saved to: {gz_path}")

In [4]:
def process_bundesland(bundesland_id, region_name=None, input_folder="prep/tile_cache", output_folder="output", max_workers=3, limit_tiles=None):
    print(f"▶️ Starte Verarbeitung für {bundesland_id}...")

    metadata_path = os.path.join(output_folder, "ml-mf_metadata.json")

    tiles = load_tiles_from_json(bundesland_id, input_folder=input_folder)
    if limit_tiles:
        tiles = tiles[:limit_tiles]

    # Token einmal laden, nicht pro Tile
    with open("config.json") as f:
        access_token = json.load(f)["ACCESS_TOKEN"]

    def process_tile(tile):
        tile_layer = 'point'  # #'traffic_sign'  # already defined
        tile_coverage = 'mly_map_feature_point'  # "mly_map_feature_traffic_sign"

        url = f"https://tiles.mapillary.com/maps/vtp/{tile_coverage}/2/{tile.z}/{tile.x}/{tile.y}?access_token={access_token}"

        # WICHTIG: requests.get MUSS ein timeout haben. Ohne timeout blockiert ein
        # gestrandeter Socket (z. B. nach einem gluetun/VPN-Reconnect) unbegrenzt und
        # legt den ganzen ThreadPool lahm -> der Lauf steht still (beobachtet: >5 h
        # Hänger an DE-HE nach VPN-Reconnect). (connect=10s, read=30s) + begrenzte
        # Retries mit Backoff; RequestException deckt Timeout/ConnectionError/SSLError ab.
        response = None
        for attempt in range(4):
            try:
                response = requests.get(url, timeout=(10, 30))
                break
            except requests.exceptions.RequestException as e:
                if attempt == 3:
                    print(f"❌ Tile {tile.x}/{tile.y}: {attempt + 1} Versuche fehlgeschlagen ({e}) — übersprungen")
                    return None
                time.sleep(min(30, 2 ** attempt))

        if response is None or response.status_code != 200:
            return None
        try:
            geojson = vt_bytes_to_geojson(response.content, tile.x, tile.y, tile.z, layer=tile_layer)
            features = geojson.get("features", [])
            if not features:
                return None
            gdf_tile = gpd.GeoDataFrame.from_features(features, crs="EPSG:4326")
            # Pin the id dtype: a later concat with a tile that lacks the column
            # would turn plain int64 into float64 and silently round every id
            # above 2**53. Nullable Int64 stays exact and NA-safe.
            if "id" in gdf_tile.columns:
                gdf_tile["id"] = gdf_tile["id"].astype("Int64")
            gdf_tile['first_seen_at'] = gdf_tile['first_seen_at'].apply(lambda x: datetime.fromtimestamp(x / 1000, tz=timezone.utc)).dt.strftime('%Y-%m-%d')
            gdf_tile['last_seen_at'] = gdf_tile['last_seen_at'].apply(lambda x: datetime.fromtimestamp(x / 1000, tz=timezone.utc)).dt.strftime('%Y-%m-%d')
            gdf_tile['tile_x'] = tile.x
            gdf_tile['tile_y'] = tile.y
            return gdf_tile
        except Exception as e:
            print(f"❌ Fehler bei Tile {tile.x}/{tile.y}: {e}")
            return None

    gdf_all = []
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(process_tile, tile): tile for tile in tiles}
        for future in tqdm(as_completed(futures), total=len(futures), desc=f"🧩 {bundesland_id}"): #, leave=False
            try:
                result = future.result()
                if result is not None:
                    gdf_all.append(result)
                # Future-Referenz auf das Tile-GDF auflösen, sonst bleibt es
                # bis zum Funktionsende gepinnt (Future._result).
                del result
                futures.pop(future, None)
            except SSLError as e:
                print(f"⚠️ SSLError: {e}. Pausiere für 5 Minuten...")
                time.sleep(300)  # 5 Minuten Pause
            except Exception as e:
                print(f"⚠️ Unbekannter Fehler: {e}")

    if gdf_all:
        # Concat zuerst, dann Liste sofort leeren -> Tile-GDFs werden freigegeben,
        # bevor der Export den nächsten Memory-Peak verursacht.
        gdf_concat = gpd.GeoDataFrame(pd.concat(gdf_all, ignore_index=True))
        gdf_all.clear()
        gc.collect()
        export_geodata(
            gdfs=gdf_concat,
            output_folder=output_folder,
            region=bundesland_id,
            save_parquet=True,
            save_geojson_gz=False,
            metadata_path=metadata_path,
            bundesland_id=bundesland_id,
        )
        del gdf_concat
    else:
        print(f"⚠️ Keine Daten für {bundesland_id}.")

    # RAM freigeben bevor das nächste Bundesland startet
    del tiles, futures
    gc.collect()

In [5]:
bland = gpd.read_file("https://raw.githubusercontent.com/isellsoap/deutschlandGeoJSON/main/2_bundeslaender/1_sehr_hoch.geo.json")
bland#[15:]

,id,name,type,geometry
0,DE-BW,Baden-Württemberg,State,"MULTIPOLYGON (((8.70837 47.71556, 8.70918 47.7..."
1,DE-BY,Bayern,State,"POLYGON ((10.13386 50.55, 10.1398 50.54252, 10..."
2,DE-BE,Berlin,State,"POLYGON ((13.16181 52.59442, 13.174 52.59425, ..."
3,DE-BB,Brandenburg,State,"POLYGON ((13.87951 53.50107, 13.87927 53.49908..."
4,DE-HB,Bremen,State,"POLYGON ((8.98545 53.12822, 8.97316 53.12799, ..."
5,DE-HH,Hamburg,State,"POLYGON ((10.07162 53.71823, 10.0715 53.72192,..."
6,DE-HE,Hessen,State,"POLYGON ((9.49877 51.63152, 9.50474 51.62795, ..."
7,DE-MV,Mecklenburg-Vorpommern,State,"MULTIPOLYGON (((14.26472 53.71069, 14.26472 53..."
8,DE-NI,Niedersachsen,State,"MULTIPOLYGON (((6.86528 53.59597, 6.86528 53.5..."
9,DE-NW,Nordrhein-Westfalen,State,"POLYGON ((8.66628 52.52528, 8.67277 52.51795, ..."
10,DE-RP,Rheinland-Pfalz,State,"POLYGON ((7.79963 50.94302, 7.81179 50.93973, ..."
11,DE-SL,Saarland,State,"POLYGON ((7.03796 49.64338, 7.0559 49.63674, 7..."
12,DE-ST,Sachsen-Anhalt,State,"POLYGON ((11.63251 53.01641, 11.63239 53.00897..."
13,DE-SN,Sachsen,State,"POLYGON ((12.878 51.6727, 12.87185 51.6691, 12..."
14,DE-SH,Schleswig-Holstein,State,"MULTIPOLYGON (((8.68972 54.06681, 8.68972 54.0..."
15,DE-TH,Thüringen,State,"POLYGON ((10.77189 51.64491, 10.78391 51.64098..."

In [6]:
bland[4:5]

      id    name   type                                           geometry
4  DE-HB  Bremen  State  POLYGON ((8.98545 53.12822, 8.97316 53.12799, ...

In [7]:

# Alle Bundesländer im tile_cache verarbeiten

bland = gpd.read_file("https://raw.githubusercontent.com/isellsoap/deutschlandGeoJSON/main/2_bundeslaender/1_sehr_hoch.geo.json")

#for _, row in bland[4:5].iterrows():
#for _, row in bland[15:].iterrows():
for _, row in bland.iterrows():

    b_id = row["id"]
    name = row["name"]

    # Nur verarbeiten, wenn eine JSON-Datei existiert
    tile_json_path = os.path.join("prep/tile_cache", f"{b_id}_tiles.json")
    if not os.path.exists(tile_json_path):
        print(f"⏩ Überspringe {b_id}, keine Tiles gefunden.")
        continue

    process_bundesland(b_id, region_name=name)
    gc.collect()

▶️ Starte Verarbeitung für DE-BW...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-BW_latest.parquet
▶️ Starte Verarbeitung für DE-BY...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-BY_latest.parquet
▶️ Starte Verarbeitung für DE-BE...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-BE_latest.parquet

▶️ Starte Verarbeitung für DE-BB...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-BB_latest.parquet
▶️ Starte Verarbeitung für DE-HB...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-HB_latest.parquet
▶️ Starte Verarbeitung für DE-HH...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-HH_latest.parquet
▶️ Starte Verarbeitung für DE-HE...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-HE_latest.parquet
▶️ Starte Verarbeitung für DE-MV...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-MV_latest.parquet
▶️ Starte Verarbeitung für DE-NI...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-NI_latest.parquet
▶️ Starte Verarbeitung für DE-NW...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-NW_latest.parquet

▶️ Starte Verarbeitung für DE-RP...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-RP_latest.parquet
▶️ Starte Verarbeitung für DE-SL...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-SL_latest.parquet
▶️ Starte Verarbeitung für DE-ST...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-ST_latest.parquet
▶️ Starte Verarbeitung für DE-SN...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-SN_latest.parquet
▶️ Starte Verarbeitung für DE-SH...

✔ Parquet saved to: output/mapillary_map-feature-points_DE-SH_latest.parquet
▶️ Starte Verarbeitung für DE-TH...

❌ Fehler bei Tile 8725/5483: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5485: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5484: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5486: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5488: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5487: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5492: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5494: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5496: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5495: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5497: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5498: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5499: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5500: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5501: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5502: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5503: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5504: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5505: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5506: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5507: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5509: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5511: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5510: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5512: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5514: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5513: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5515: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5516: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5518: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5517: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5519: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5520: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5521: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5522: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5523: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8725/5524: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8725/5525: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5484: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5485: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5486: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5487: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5488: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5491: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5495: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5496: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5497: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5498: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5500: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5499: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5501: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5503: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5504: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5502: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5505: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5506: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5507: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5510: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5509: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5511: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5512: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5513: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5514: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5516: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5515: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5518: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5517: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5521: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5520: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5519: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8726/5522: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5523: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8726/5524: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5484: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5485: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5486: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5487: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5488: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5490: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5492: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5493: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5495: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5496: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5497: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5498: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5501: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5500: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5499: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5503: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5502: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5504: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5505: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5506: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5507: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5508: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5510: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5511: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5512: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5514: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5513: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5509: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5515: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5517: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5516: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5518: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5519: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5521: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5520: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5522: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8727/5523: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8727/5524: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5484: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5485: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5486: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5487: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5488: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5491: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5490: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5495: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5496: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5497: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5499: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5498: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5500: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5501: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5503: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5502: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5505: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5504: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5506: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5509: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5510: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5507: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5511: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5512: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5513: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5515: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5514: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5518: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5516: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5517: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5521: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5520: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8728/5519: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5523: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5522: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5483: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8728/5524: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5484: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5486: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5485: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5487: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5488: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5491: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5495: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5497: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5496: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5498: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5499: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5500: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5501: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5503: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5502: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5504: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5505: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5506: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5507: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5509: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5511: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5510: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5512: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5513: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5514: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5515: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5516: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5518: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5517: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5521: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5519: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5522: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8729/5523: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5524: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5483: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8729/5520: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5484: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5485: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5486: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5487: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5488: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5490: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5492: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5493: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5495: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5496: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5497: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5499: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5500: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5501: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5502: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5503: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5505: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5504: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5498: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5507: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5506: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5509: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5510: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5511: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5512: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5513: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5514: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5515: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5517: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5516: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5518: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5519: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5520: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8730/5521: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5522: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5483: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5523: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5484: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5486: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5485: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5487: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8730/5524: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5488: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5495: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5497: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5498: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5499: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5496: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5500: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5501: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5502: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5504: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5506: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5507: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5503: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5505: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5509: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5510: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5511: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5512: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5513: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5514: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5515: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5516: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5517: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5518: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5519: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5520: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5521: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5522: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8731/5523: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8731/5524: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5483: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5484: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5485: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5487: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5488: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5486: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5493: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5495: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5497: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5498: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5496: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5500: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5501: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5499: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5502: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5504: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5503: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5505: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5507: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5506: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5508: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5509: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5512: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5510: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5511: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5513: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5514: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8732/5521: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8732/5522: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8733/5484: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8733/5485: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8733/5487: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8733/5486: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8733/5488: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8733/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8733/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8733/5490: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8733/5492: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8733/5494: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8733/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8733/5495: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8733/5496: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8733/5498: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8733/5499: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8733/5500: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8733/5501: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8733/5502: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8733/5503: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8733/5504: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8733/5505: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8733/5497: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8733/5506: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8733/5507: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8733/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8733/5509: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8733/5510: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8733/5511: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8733/5512: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8734/5486: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8734/5485: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8734/5488: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8734/5487: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8733/5521: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8734/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8734/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8734/5491: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8734/5492: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8734/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8734/5493: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8734/5495: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8734/5496: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8734/5497: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8734/5499: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8734/5498: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8734/5502: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8734/5501: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8734/5500: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8734/5503: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8734/5504: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8734/5505: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8734/5506: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8734/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8734/5507: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8734/5511: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8734/5510: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8734/5512: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8734/5509: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8735/5487: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8735/5488: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8735/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8735/5486: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8735/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8735/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8735/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8735/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8735/5494: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8735/5495: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8735/5496: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8735/5497: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8735/5498: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8735/5500: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8735/5499: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8735/5501: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8735/5503: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8735/5504: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8735/5505: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8735/5507: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8735/5506: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8735/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8735/5502: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8735/5509: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8735/5510: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8736/5487: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8736/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8736/5488: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8736/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8736/5492: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8736/5491: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8736/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8736/5494: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8736/5496: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8736/5497: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8736/5498: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8736/5499: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8736/5500: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8736/5501: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8736/5495: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8736/5504: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8736/5505: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8736/5503: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8736/5502: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8736/5506: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8736/5507: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8736/5509: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8736/5508: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8737/5488: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8737/5490: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8737/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8737/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8737/5492: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8737/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8737/5494: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8737/5495: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8737/5497: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8737/5496: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8737/5498: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8737/5499: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8737/5500: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8737/5501: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8737/5502: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8737/5504: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8737/5503: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8737/5505: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8737/5506: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8737/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8737/5509: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8738/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8738/5490: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8737/5507: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8738/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8738/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8738/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8738/5495: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8738/5494: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8738/5496: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8738/5497: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8738/5498: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8738/5500: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8738/5499: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8738/5501: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8738/5503: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8738/5502: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8738/5504: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8738/5505: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8738/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8738/5507: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8739/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8739/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8739/5490: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8739/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8738/5506: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8739/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8739/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8739/5495: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8739/5496: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8739/5497: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8739/5499: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8739/5501: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8739/5500: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8739/5502: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8739/5503: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8739/5504: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8739/5505: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8739/5498: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8739/5507: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8739/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8739/5506: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8740/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8740/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8740/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8740/5492: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8740/5493: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8740/5496: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8740/5494: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8740/5498: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8740/5497: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8740/5500: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8740/5501: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8740/5495: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8740/5502: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8740/5503: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8740/5504: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8740/5499: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8740/5505: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8740/5506: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8740/5507: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8740/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8740/5509: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8741/5490: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8741/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8741/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8741/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8741/5493: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8741/5495: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8741/5496: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8741/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8741/5498: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8741/5497: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8741/5500: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8741/5499: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8741/5501: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8741/5503: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8741/5504: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8741/5505: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8741/5506: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8741/5507: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8741/5508: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8741/5509: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8741/5510: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8741/5502: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8742/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8742/5490: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8742/5491: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8742/5492: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8742/5493: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8742/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8742/5495: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8741/5511: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8742/5497: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8742/5499: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8742/5500: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8742/5501: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8742/5496: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8742/5498: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8742/5502: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8742/5504: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8742/5503: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8742/5506: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8742/5505: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8742/5507: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8742/5509: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8742/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8742/5510: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8743/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8742/5512: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8742/5511: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8743/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8743/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8743/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8743/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8743/5494: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8743/5495: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8743/5496: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8743/5497: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8743/5500: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8743/5498: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8743/5501: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8743/5502: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8743/5503: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8743/5505: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8743/5504: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8743/5499: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8743/5506: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8743/5507: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8743/5508: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8743/5509: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8743/5510: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8744/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8744/5491: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8744/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8744/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8744/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8744/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8744/5495: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8744/5496: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8744/5498: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8744/5497: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8744/5499: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8744/5500: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8744/5502: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8744/5501: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8744/5504: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8744/5505: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8744/5506: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8744/5507: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8744/5508: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8744/5509: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8744/5503: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8745/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8745/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8745/5490: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8745/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8745/5493: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8745/5495: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8745/5496: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8745/5497: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8745/5498: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8745/5492: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8745/5499: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8745/5500: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8745/5502: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8745/5503: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8745/5504: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8745/5505: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8745/5506: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8745/5507: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8745/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8745/5501: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8746/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8746/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8746/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8746/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8746/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8746/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8746/5495: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8746/5496: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8746/5497: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8746/5499: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8746/5501: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8746/5502: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8746/5498: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8746/5503: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8746/5504: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8746/5505: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8746/5506: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8746/5507: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8746/5500: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8746/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8747/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8747/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8747/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8747/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8747/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8747/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8747/5495: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8747/5497: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8747/5498: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8747/5496: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8747/5500: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8747/5499: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8747/5504: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8747/5506: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8747/5505: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8747/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8748/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8748/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8748/5491: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8748/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8748/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8747/5507: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8748/5495: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8748/5506: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8748/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8748/5507: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8748/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8749/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8749/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8749/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8749/5493: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8749/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8749/5495: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8750/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8749/5508: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8749/5490: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8750/5491: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8750/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8750/5490: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8750/5494: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8751/5487: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8750/5492: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8750/5495: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8751/5488: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8751/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8751/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8751/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8751/5492: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8751/5493: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8751/5494: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8752/5486: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8752/5487: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8752/5488: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8752/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8752/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8752/5491: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8752/5492: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8752/5494: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8753/5480: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8753/5486: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8753/5485: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8753/5488: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8753/5487: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8753/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8752/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8753/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8753/5492: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8753/5491: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8754/5481: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8753/5494: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8754/5482: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8754/5483: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8754/5484: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8753/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8754/5485: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8754/5486: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8754/5487: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8754/5488: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8754/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8754/5490: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8754/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8755/5481: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8755/5482: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8754/5491: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8754/5493: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8755/5483: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8755/5484: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8755/5485: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8755/5487: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8755/5486: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8755/5488: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8755/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8755/5491: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8755/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8756/5481: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8755/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8756/5483: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8756/5482: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8756/5485: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8756/5484: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8756/5486: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8756/5487: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8756/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8756/5490: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8756/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8756/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8757/5481: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8756/5488: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8757/5482: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8757/5483: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8757/5486: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8757/5484: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8757/5485: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8757/5487: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8757/5488: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8757/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8757/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8757/5492: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8757/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8758/5481: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8758/5483: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8758/5482: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8758/5484: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8758/5485: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8758/5488: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8758/5487: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8758/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8758/5490: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8758/5491: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8759/5482: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8758/5486: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8759/5483: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8759/5484: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8759/5485: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8759/5486: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8759/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8759/5488: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8759/5490: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8759/5487: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8760/5485: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8760/5486: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8760/5488: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8760/5487: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8760/5489: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8761/5487: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8761/5486: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8761/5488: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8762/5488: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8762/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8763/5487: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8761/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8763/5488: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8762/5487: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8763/5489: Error parsing message with type 'vector_tile.tile'

❌ Fehler bei Tile 8764/5488: Error parsing message with type 'vector_tile.tile'
❌ Fehler bei Tile 8764/5489: Error parsing message with type 'vector_tile.tile'

✔ Parquet saved to: output/mapillary_map-feature-points_DE-TH_latest.parquet